### ISSUE TITLE
error aggregate in logstash 5.0

### ISSUE THREAD

**Issue by simpleuser99** [logstash-plugins/logstash-filter-aggregate#48]
Hello
When I use logstash 2.4 I didn't have problem. But when I use logstash 5.0 my config is not work.
I have the next error
`[ERROR][logstash.filters.aggregate] Aggregate exception occurred {:error=>#<NoMethodError: Direct event field references (i.e. event['field']) have been disabled in favor of using event get and set methods (e.g. event.get('field')). Please consult the Logstash 5.0 breaking changes documentation for more details.>`
What is it?

**Comment by fbaligand** [comment]
Hi @simpleuser99 

It is not due to an aggregate plugin bug, but rather to Logstash Event API which has changed between Logstash 2.4 and Logstash 5 : a breaking change.

With Logstash 5, you can't use `event['field']` anymore.
You have to use either `event.get('field')` either `event.set('field', 'value')`

aggregate examples have been updated to be compatible with Logstash 5 here :
https://github.com/logstash-plugins/logstash-filter-aggregate/#example-1

**Comment by fbaligand** [comment]
I close the issue, given that question is answered.

**Comment by simpleuser99** [comment]
Thank you for advise.

**Comment by fbaligand** [comment]
You're welcome :)
