### ISSUE TITLE
Events are not aggregated properly [logstash-filter-aggregate (2.7.2)]

### ISSUE THREAD

**Issue by isadp** [logstash-plugins/logstash-filter-aggregate#79]
Hi, I am not sure if it is a bug or a wrong configuration. I want to aggregate the contents of the"from" and "to" events from a sendmail log into one event. 

About 3% of the existing pairs are not aggregated in the output.

Here is my config:
```
filter {
	if ([message] =~ /from=/) {
		grok {
			match => {"message" => "%{SYSLOGTIMESTAMP:[from][date]} mail sm-mta\[%{BASE10NUM:[from][smmta]}\]: %{DATA:hash}: from=<%{DATA:[from][mail]}> ..."}
		}
		aggregate {
			task_id => "%{hash}"
			code => "map['[from]'] = event.get('[from]')"
			map_action => "create"
			push_map_as_event_on_timeout => true
			timeout_task_id_field => "hash"
			inactivity_timeout => 240
			timeout => 61516800
			timeout_tags => ["aggregate_timeout"]
		}
		if "aggregate_timeout" not in [tags] {
			drop{}
		}
	}
	else {
		grok {
			match => {"message" => "%{SYSLOGTIMESTAMP:[to][date]} mail sm-mta\[%{BASE10NUM:[to][smmta]}\]: %{DATA:hash}: to=%{DATA:[to][mail]}, ..."}
		}
		aggregate {
			task_id => "%{hash}"
			code => "event.set('[from]', map['[from]'])"
			map_action => "update"
			end_of_task => true
		}
	}
}
```
Is there a maximum of open maps that the aggregate filter can hold?
  
logstash 6.1.1
logstash-filter-aggregate 2.7.2

**Comment by fbaligand** [comment]
Hi @isadp,

First, your configuration looks fine for your need. I don't see any misconfiguration here.

Then, so that your Logstash configuration works fine, you have to be sure to have only one thread for your pipeline.
So you have to set `-w 1` as command line flag in your Logstash startup. Or you can define it in `pipelines.yml`.
If you don't do that, some "to" lines could be processed before "from" lines, and so, aggregate code is not executed as `map_action` condition is not matched.

Finally, some questions : 
- are you sure 100% of your sendmail log lines have first a "from" line, then a "to" line ?
- are your sure that you have maxi 240s between "from" line event and "to" line event ?
- do you have some "aggregate_timeout" tagged events ? Are they the 3% other cases ?

**Comment by isadp** [comment]
Hi,
I have a set of data for testing which is shipped via filebeat to redis to logstash.
A "from" event always turns up before the "to" events.
As I am shipping the data from a file to logstash I think the timeout of 240 secs is enough.
The pipeline is set to one worker. 
All events which are not aggregated properly are "from" events from a "aggregate_timeout".

But I think i have found what is causing the aggregate errors:
We have a lot of mails with connections timeouts and related errors - in this case the mail server tries to send one mail over several days and many "to" events are assigned to one "from" event. 
After a first "to" event the aggregation is completed and the "from" map is cleared. 
I think the following "to" events are flooding the aggregate filter by searching the map
for the non existing task_id.

For testing I have removed the overhead of the "to" lines from my test file - with this file I get the expected results.

**Comment by fbaligand** [comment]
Nice to see you found the root cause of your problem !
